

from PIL import Image
import matplotlib.pyplot as plt
import numpy as np

#Spades
king_spades = Image.open('king_spades.png')
queen_spades = Image.open('queen_spades.png')
jack_spades = Image.open('jack_spades.png')
ten_spades = Image.open('10_spades.png')
nine_spades = Image.open('9_spades.png')
eight_spades = Image.open('8_spades.png')
seven_spades = Image.open('7_spades.png')
six_spades = Image.open('6_spades.png')
five_spades = Image.open('5_spades.png')
four_spades = Image.open('4_spades.png')
three_spades = Image.open('3_spades.png')
two_spades = Image.open('2_spades.png')
ace_spades = Image.open('ace_spades.png')

#Hearts
king_hearts = Image.open('king_hearts.png')
queen_hearts = Image.open('queen_hearts.png')
jack_hearts = Image.open('jack_hearts.png')
ten_hearts = Image.open('10_hearts.png')
nine_hearts = Image.open('9_hearts.png')
eight_hearts = Image.open('8_hearts.png')
seven_hearts = Image.open('7_hearts.png')
six_hearts = Image.open('6_hearts.png')
five_hearts = Image.open('5_hearts.png')
four_hearts = Image.open('4_hearts.png')
three_hearts = Image.open('3_hearts.png')
two_hearts = Image.open('2_hearts.png')
ace_hearts = Image.open('ace_hearts.png')


#Clubs
king_clubs = Image.open('king_CLUBS.png')
queen_clubs = Image.open('queen_clubs.png')
jack_clubs = Image.open('jack_clubs.png')
ten_clubs = Image.open('10_clubs.png')
nine_clubs = Image.open('9_clubs.png')
eight_clubs = Image.open('8_clubs.png')
seven_clubs = Image.open('7_clubs.png')
six_clubs = Image.open('6_clubs.png')
five_clubs = Image.open('5_clubs.png')
four_clubs = Image.open('4_clubs.png')
three_clubs = Image.open('3_clubs.png')
two_clubs = Image.open('2_clubs.png')
ace_clubs = Image.open('ace_clubs.png')

#Diamonds
king_diamonds = Image.open('king_diamonds.png')
queen_diamonds = Image.open('queen_diamonds.png')
jack_diamonds = Image.open('jack_diamonds.png')
ten_diamonds = Image.open('10_diamonds.png')
nine_diamonds = Image.open('9_diamonds.png')
eight_diamonds = Image.open('8_diamonds.png')
seven_diamonds = Image.open('7_diamonds.png')
six_diamonds = Image.open('6_diamonds.png')
five_diamonds = Image.open('5_diamonds.png')
four_diamonds = Image.open('4_diamonds.png')
three_diamonds = Image.open('3_diamonds.png')
two_diamonds = Image.open('2_diamonds.png')
ace_diamonds = Image.open('ace_diamonds.png')

newsize = (300,450)

def show_image():
    
    #resized spades
    resized_king_spades = king_spades.resize(newsize,Image.BILINEAR)
    resized_queen_spades = queen_spades.resize(newsize,Image.BILINEAR)
    resized_jack_spades = jack_spades.resize(newsize,Image.BILINEAR)
    resized_ten_spades = ten_spades.resize(newsize,Image.BILINEAR)
    resized_nine_spades = nine_spades.resize(newsize,Image.BILINEAR)
    resized_eight_spades = eight_spades.resize(newsize,Image.BILINEAR)
    resized_seven_spades = seven_spades.resize(newsize,Image.BILINEAR)
    resized_six_spades = six_spades.resize(newsize,Image.BILINEAR)
    resized_five_spades = five_spades.resize(newsize,Image.BILINEAR)
    resized_four_spades = four_spades.resize(newsize,Image.BILINEAR)
    resized_three_spades = three_spades.resize(newsize,Image.BILINEAR)
    resized_two_spades = two_spades.resize(newsize,Image.BILINEAR)
    resized_ace_spades = ace_spades.resize(newsize,Image.BILINEAR)
    
    #resized hearts
    resized_king_hearts = king_hearts.resize(newsize,Image.BILINEAR)
    resized_queen_hearts = queen_hearts.resize(newsize,Image.BILINEAR)
    resized_jack_hearts = jack_hearts.resize(newsize,Image.BILINEAR)
    resized_ten_hearts = ten_hearts.resize(newsize,Image.BILINEAR)
    resized_nine_hearts = nine_hearts.resize(newsize,Image.BILINEAR)
    resized_eight_hearts = eight_hearts.resize(newsize,Image.BILINEAR)
    resized_seven_hearts = seven_hearts.resize(newsize,Image.BILINEAR)
    resized_six_hearts = six_hearts.resize(newsize,Image.BILINEAR)
    resized_five_hearts = five_hearts.resize(newsize,Image.BILINEAR)
    resized_four_hearts = four_hearts.resize(newsize,Image.BILINEAR)
    resized_three_hearts = three_hearts.resize(newsize,Image.BILINEAR)
    resized_two_hearts = two_hearts.resize(newsize,Image.BILINEAR)
    resized_ace_hearts = ace_hearts.resize(newsize,Image.BILINEAR)
     
    #resized clubs
    resized_king_clubs = king_clubs.resize(newsize,Image.BILINEAR)
    resized_queen_clubs = queen_clubs.resize(newsize,Image.BILINEAR)
    resized_jack_clubs = jack_clubs.resize(newsize,Image.BILINEAR)
    resized_ten_clubs = ten_clubs.resize(newsize,Image.BILINEAR)
    resized_nine_clubs = nine_clubs.resize(newsize,Image.BILINEAR)
    resized_eight_clubs = eight_clubs.resize(newsize,Image.BILINEAR)
    resized_seven_clubs = seven_clubs.resize(newsize,Image.BILINEAR)
    resized_six_clubs = six_clubs.resize(newsize,Image.BILINEAR)
    resized_five_clubs = five_clubs.resize(newsize,Image.BILINEAR)
    resized_four_clubs = four_clubs.resize(newsize,Image.BILINEAR)
    resized_three_clubs = three_clubs.resize(newsize,Image.BILINEAR)
    resized_two_clubs = two_clubs.resize(newsize,Image.BILINEAR)
    resized_ace_clubs = ace_clubs.resize(newsize,Image.BILINEAR)
      
    #resized diamonds
    resized_king_diamonds = king_diamonds.resize(newsize,Image.BILINEAR)
    resized_queen_diamonds = queen_diamonds.resize(newsize,Image.BILINEAR)
    resized_jack_diamonds = jack_diamonds.resize(newsize,Image.BILINEAR)
    resized_ten_diamonds = ten_diamonds.resize(newsize,Image.BILINEAR)
    resized_nine_diamonds = nine_diamonds.resize(newsize,Image.BILINEAR)
    resized_eight_diamonds = eight_diamonds.resize(newsize,Image.BILINEAR)
    resized_seven_diamonds = seven_diamonds.resize(newsize,Image.BILINEAR)
    resized_six_diamonds = six_diamonds.resize(newsize,Image.BILINEAR)
    resized_five_diamonds = five_diamonds.resize(newsize,Image.BILINEAR)
    resized_four_diamonds = four_diamonds.resize(newsize,Image.BILINEAR)
    resized_three_diamonds = three_diamonds.resize(newsize,Image.BILINEAR)
    resized_two_diamonds = two_diamonds.resize(newsize,Image.BILINEAR)
    resized_ace_diamonds = ace_diamonds.resize(newsize,Image.BILINEAR)
    
    
    #showing the hand image
    hand_img = Image.new('RGB', (1200,450))
    #hand_img.paste(resized_five_spades, (0,0))
    #hand_img.paste(resized_ace_hearts, (300,0))
    #hand_img.paste(resized_four_clubs, (600,0))
    #hand_img.paste(resized_jack_diamonds, (900,0))
    plt.imshow(hand_img)
    plt.show()
    
    hand_img = Image.new('RGB', (1200,450))
    hand_img.paste(resized_five_spades, (0,0))
    #hand_img.paste(resized_ace_hearts, (300,0))
    #hand_img.paste(resized_four_clubs, (600,0))
    #hand_img.paste(resized_jack_diamonds, (900,0))
    plt.imshow(hand_img)
    plt.show()
    
    hand_img = Image.new('RGB', (1200,450))
    hand_img.paste(resized_five_spades, (0,0))
    hand_img.paste(resized_ace_hearts, (300,0))
    #hand_img.paste(resized_four_clubs, (600,0))
    #hand_img.paste(resized_jack_diamonds, (900,0))
    plt.imshow(hand_img)
    plt.show()
    
    hand_img = Image.new('RGB', (1200,450))
    hand_img.paste(resized_five_spades, (0,0))
    hand_img.paste(resized_ace_hearts, (300,0))
    hand_img.paste(resized_four_clubs, (600,0))
    #hand_img.paste(resized_jack_diamonds, (900,0))
    plt.imshow(hand_img)
    plt.show()
    
    hand_img = Image.new('RGB', (1200,450))
    hand_img.paste(resized_five_spades, (0,0))
    hand_img.paste(resized_ace_hearts, (300,0))
    hand_img.paste(resized_four_clubs, (600,0))
    hand_img.paste(resized_jack_diamonds, (900,0))
    plt.imshow(hand_img)
    plt.show()

show_image()
